### ISSUE TITLE
Do you guys have ideas on how to present our pup-up book on the presentation?

### ISSUE THREAD

**Issue by wenqicai1** [taiyang777/scottishpeople#2]

**Comment by renning890726** [comment]
please use a structure as follows:
Context: 1 min on the context you are working on - help us understand why it is important and interesting.
Data: 1 min on the data that you have - what you saw in it, if you connected it to other data, any particularly interesting processing or features that you derived.
Audience: 1 min on your audience and what you are trying to convey with your piece. Note: "The general public" is a rubbish audience - be more specific about who you are communicating to and why. This is how we will look at your presentation.
Demo: 2 mins demoing, presenting, walking through or otherwise showing your wo
Suggestions:

Practice with a stopwatch - we're going to be quite strict with time
Know who is going to speak when
Tell us the most interesting bits - don't list every field, or every step of your data analysis pipeline - figure out what is interesting, and just tell us those bits.
Practice with people who don't know your data, speak a different language etc. Find out what is and is not clear to them, what is interesting.

**Comment by taiyang777** [comment]
actually, I've found a lot of tutorials to show how to diy a pop-up book, which can include many interactive methods. But more importantly, we still need to keep in mind: functions are not more important than our actual data.

**Comment by taiyang777** [comment]
I think for our target audience and storyline, we need to discuss after tomorrow. "How to construct our story"

**Comment by renning890726** [comment]
I think we have already set a good target audience group and story outline, but rehearsal and practice are necessary to tell a great story

**Comment by renning890726** [comment]
time will be limited and be assessed strictly when we make presentation, which is what we need to keep in mind.

**Comment by taiyang777** [comment]
@renning890726  yes, I agree with u, but I am just thinking something like memory? 2 generations communication? or a better word?

**Comment by wenqicai1** [comment]
Yep,you are right,and maybe we can talk about the acquirement of the presentation in detail tomorrow,and to define how can we present our story!

**Comment by renning890726** [comment]
time machine or time capsule or memory album

**Comment by wenqicai1** [comment]
memory album is better i think!
